name: Publish Release

on:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write

jobs:
  sync-latest-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - run: |
          git checkout -f -b latest origin/latest
          git merge --ff-only origin/main
          git push origin latest

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
        with:
          bun-version-file: .tool-versions
      - run: bunx jsr publish
